# Generated by Django 5.2.6 on 2025-10-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_options_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'Can View History')]},
        ),
    ]
